### ISSUE TITLE
秒传或者续传文件，上传过程中点击取消或者删除报错

### ISSUE THREAD

**Issue by hin-longkid** [devin87/web-uploader#1]
运行环境：
Windows 7
Chrome 版本 51.0.2704.84

代码版本：
Q.Uploader.js 文件上传管理器 1.0
update:2017/02/09 09:03

秒传或者续传文件，上传过程中点击取消或者删除报错
Uncaught TypeError: Cannot read property 'contentWindow' of undefined     Q.Uploader.js:512

debug之后发现
Q.Uploader.slice.js line:28 需要添加一行
task.xhr = xhr; //通过html5上传

**Comment by devin87** [comment]
谢谢反馈，已修复。
