### ISSUE TITLE
complete 的回调竟然没有触发控件本身？

### ISSUE THREAD

**Issue by huangli58** [devin87/web-uploader#28]
比如，我的 target = "#upload-image" 。上传成功后，我希望有一个 this 可以指向 upload-image 本身，这样我才能够做出更好上传的效果。莫非是我没有看到？

**Comment by devin87** [comment]
提问前请先看下文档和demo，回调函数中task参数有你想要的input元素。你要实在想this指向input，可以自行修改源码。

**Comment by huangli58** [comment]
我看了源码，这个input是由js生成的，并非是触发控件。

**Comment by devin87** [comment]
1. 不知道你要实现什么效果
2. #upload-image（并非 <input type='file'> 元素）是你传给上传组件的，你已经得到了，还要在回调函数里取吗；如果你传的是个数组，你想知道点了哪个上传按钮，你需要自行添加事件监控。
3. 如果你想获取的是 <input type='file'> 元素，你可以通过 task.input 获取

**Comment by huangli58** [comment]
那我再试下，因为按照文档的方法，我传入触发控件，比如.img，因为存在多个.img，回调的时候，我想知道是哪个.img起了作用，我才能将它自身删除。
