### ISSUE TITLE
关于组件的初始化

### ISSUE THREAD

**Issue by zealze** [devin87/web-uploader#29]
如果之前已上传了几个文件，打开页面异步获取文件列表，加载这几个文件到上传组件中显示，该怎么操作呢？

**Comment by devin87** [comment]
已上传数据一般是单独显示，如果你想和上传组件显示效果一样，你可以参考上传组件的html结构来生成html代码。

**Comment by zealze** [comment]
我试试，我应该还需要在文件名称上添加下载文件的链接。
