### ISSUE TITLE
关于H5图片选择页面

### ISSUE THREAD

**Issue by WithoutHair** [devin87/web-uploader#30]
选择图片页图片都没有预览只是灰色方块是为什么呢

**Comment by devin87** [comment]
是通过 http 访问的吗？

**Comment by WithoutHair** [comment]
是的 通过IP地址访问的本地端口

**Comment by devin87** [comment]
不好意思 ，最近较忙，没来得及回复。你是运行的示例代码吗，什么浏览器？我刚测试，Firefox、Chrome、IE兼容 模式、Android 浏览器都显示正常。

**Comment by WithoutHair** [comment]
安卓chrome在限制了文件上传类型仅为图片的几种常见格式时不会直接唤起系统的相册 应该是库封装的一个选择界面？加载速度很慢 后来还是在提供的方法中做上传限制了

**Comment by WithoutHair** [comment]
好的 十分感谢您的回复
